export const REQUEST_POKEDESK = 'POKEMON/REQUEST_POKEDESK';
export const REQUEST_POKEDESK_SUCCESS = 'POKEMON/REQUEST_POKEDESK_SUCCESS';
export const REQUEST_POKEDESK_FAIL = 'POKEMON/REQUEST_POKEDESK_FAIL';

export const REQUEST_ADD_POKEMON = 'POKEMON/REQUEST_ADD_POKEMON';
export const REQUEST_ADD_POKEMON_SUCCESS = 'POKEMON/REQUEST_ADD_POKEMON_SUCCESS';
export const REQUEST_ADD_POKEMON_FAIL = 'POKEMON/REQUEST_ADD_POKEMON_FAIL';

export const REQUEST_REMOVE_POKEMON = 'POKEMON/REQUEST_REMOVE_POKEMON';
export const REQUEST_REMOVE_POKEMON_SUCCESS = 'POKEMON/REQUEST_REMOVE_POKEMON_SUCCESS';
export const REQUEST_REMOVE_POKEMON_FAIL = 'POKEMON/REQUEST_REMOVE_POKEMON_FAIL';

export const REQUEST_SEARCH_POKEMON = 'POKEMON/REQUEST_SEARCH_POKEMON';
export const REQUEST_SEARCH_POKEMON_SUCCESS = 'POKEMON/REQUEST_SEARCH_POKEMON_SUCCESS';
export const REQUEST_SEARCH_POKEMON_FAIL = 'POKEMON/REQUEST_SEARCH_POKEMON_FAIL';

